config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'dashboard#index'

  resources :teams do
    get :assign_members
    post :save_members
    resources :roles
    resources :users do 
      get :assign_roles
      post :save_roles
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:login]

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :team_members
  has_many :teams, through: :team_members

  has_many :team_owners, class_name: "Team"

  has_many :roles_users
  has_many :roles, through: :roles_users

  has_one_attached :avatar

  attr_writer :login

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = current_team.users
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        current_team.create_member(@user.id)
        format.html { redirect_to team_user_path(current_team, @user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
        params[:user].delete(:password)
        params[:user].delete(:password_confirmation)
      end
      if @user.update(user_params)
        format.html { redirect_to team_user_path(current_team, @user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to team_users_path(current_team), notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def assign_roles
    @roles = current_team.roles
    @user = User.find(params[:user_id])
    @user_roles = @user.roles
  end

  def save_roles
    if params[:role_id].present?
      roles = params[:role_id].flatten.compact
      roles.each do |id|
        RolesUser.find_or_create_by(user_id: params[:users_id], role_id: id)
      end
    end
    redirect_to team_user_path(current_team, params[:users_id]), notice: "Roles assigned successfully."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :username, :email, :avatar, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_with(model: user, url: path, class: "contents") do |form|
  - if user.errors.any?
    #error_explanation.bg-red-50.text-red-500.px-3.py-2.font-medium.rounded-lg.mt-3
      %h2
        = pluralize(user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - user.errors.each do |error|
          %li= error.full_message
  .my-5
    = form.label :first_name
    = form.text_field :first_name, required: true, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :last_name
    = form.text_field :last_name, required: true, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :username
    = form.text_field :username, oninput: "check_username(this)", required: true, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :avatar
    = form.file_field :avatar, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :email
    = form.email_field :email, required: true, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :password
    = form.password_field :password, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :password_confirmation
    = form.password_field :password_confirmation, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .inline
    = form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer"

:javascript
  function check_username(input) {
    input.value = input.value.replace(/[^a-zA-Z0-9]/g, '');
  }

app/views/users/_user.html.haml
%div{:id => "#{dom_id user}"}
  %p.my-5
    %strong.block.font-medium.mb-1 First Name:
    = user.first_name
  %p.my-5
    %strong.block.font-medium.mb-1 Last Name:
    = user.last_name
  %p.my-5
    %strong.block.font-medium.mb-1 Username:
    = user.username
  %p.my-5
    %strong.block.font-medium.mb-1 Email:
    = user.email
  %p.my-5
    %strong.block.font-medium.mb-1 Avatar:
    - if user.avatar.present?
      = image_tag user.avatar, width: 100, height: 100
  %p.my-5
    %strong.block.font-medium.mb-1 Roles:
    = user.roles&.pluck(:name)&.join(', ')
  - if action_name != "show" && (current_team.check_owner(current_user.id) || current_user.id == user.id)
    = link_to "Show this user", team_user_path(current_team.id, user), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
    = link_to "Edit this user", edit_team_user_path(user, current_team), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium"
    %hr.mt-6/

app/views/users/assign_roles.html.haml
.mx-auto.w-full{:class => "md:w-2/3"}
  %h1.font-bold.text-4xl Manage roles
  = form_with(url: team_user_save_roles_path(current_team, current_user), class: "contents") do |form|
    = form.hidden_field :users_id, value: params[:user_id]
    .my-5
      = form.label :role_id
      = form.select "role_id[]", options_for_select(@roles&.map{|v| [v.name, v.id]}, selected: @user_roles&.pluck(:id)), multiple: true, id: "role_ids"
    .inline
      = form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer"
  = link_to "Back to users", team_users_path(current_team), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/users/edit.html.haml
.mx-auto.w-full{:class => "md:w-2/3"}
  %h1.font-bold.text-4xl Editing user
  = render "form", user: @user, path: team_user_path(current_team)
  = link_to "Show this user", team_user_path(current_team, @user), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
  = link_to "Back to users", team_users_path(current_team), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/users/index.html.haml
.w-full
  - if notice.present?
    %p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block= notice
%section.py-1.bg-blueGray-50
  .w-full.mb-12.xl:mb-0.px-4.mx-auto.mt-24{class: "xl:w-8/12"}
    .relative.flex.flex-col.min-w-0.break-words.bg-white.w-full.mb-6.shadow-lg.rounded
      .rounded-t.mb-0.px-4.py-3.border-0
        .flex.flex-wrap.items-center
          .relative.w-full.px-4.max-w-full.flex-grow.flex-1
            %h3.font-semibold.text-base.text-blueGray-700 Users
          .relative.w-full.px-4.max-w-full.flex-grow.flex-1.text-right
            - if @user_roles.include?('create') || current_team.check_owner(current_user.id)
              = link_to "Create User", new_team_user_path(team_id: current_team.id), class: "bg-indigo-500 text-white active:bg-indigo-600 text-xs font-bold uppercase px-3 py-1 rounded outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150"
      .block.w-full.overflow-x-auto
        %table.items-center.bg-transparent.w-full.border-collapse
          %thead
            %tr
              %th.px-6.bg-blueGray-50.text-blueGray-500.align-middle.border.border-solid.border-blueGray-100.py-3.text-xs.uppercase.border-l-0.border-r-0.whitespace-nowrap.font-semibold.text-left
                Avatar
              %th.px-6.bg-blueGray-50.text-blueGray-500.align-middle.border.border-solid.border-blueGray-100.py-3.text-xs.uppercase.border-l-0.border-r-0.whitespace-nowrap.font-semibold.text-left
                First Name
              %th.px-6.bg-blueGray-50.text-blueGray-500.align-middle.border.border-solid.border-blueGray-100.py-3.text-xs.uppercase.border-l-0.border-r-0.whitespace-nowrap.font-semibold.text-left
                Last Name
              %th.px-6.bg-blueGray-50.text-blueGray-500.align-middle.border.border-solid.border-blueGray-100.py-3.text-xs.uppercase.border-l-0.border-r-0.whitespace-nowrap.font-semibold.text-left
                Username
              %th.px-6.bg-blueGray-50.text-blueGray-500.align-middle.border.border-solid.border-blueGray-100.py-3.text-xs.uppercase.border-l-0.border-r-0.whitespace-nowrap.font-semibold.text-left
                Email
              %th.px-6.bg-blueGray-50.text-blueGray-500.align-middle.border.border-solid.border-blueGray-100.py-3.text-xs.uppercase.border-l-0.border-r-0.whitespace-nowrap.font-semibold.text-left
                Manage Roles
              %th.px-6.bg-blueGray-50.text-blueGray-500.align-middle.border.border-solid.border-blueGray-100.py-3.text-xs.uppercase.border-l-0.border-r-0.whitespace-nowrap.font-semibold.text-left
                View
              %th.px-6.bg-blueGray-50.text-blueGray-500.align-middle.border.border-solid.border-blueGray-100.py-3.text-xs.uppercase.border-l-0.border-r-0.whitespace-nowrap.font-semibold.text-left
                Edit
              %th.px-6.bg-blueGray-50.text-blueGray-500.align-middle.border.border-solid.border-blueGray-100.py-3.text-xs.uppercase.border-l-0.border-r-0.whitespace-nowrap.font-semibold.text-left
                Delete
          %tbody
            - @users&.each do |user|
              %tr
                %td.border-t-0.px-6.align-middle.border-l-0.border-r-0.text-xs.whitespace-nowrap.p-4.text-left.text-blueGray-700
                  - if user.avatar.present?
                    = image_tag user.avatar, width: 100, height: 100
                %td.border-t-0.px-6.align-middle.border-l-0.border-r-0.text-xs.whitespace-nowrap.p-4.text-left.text-blueGray-700
                  = user.first_name
                %td.border-t-0.px-6.align-middle.border-l-0.border-r-0.text-xs.whitespace-nowrap.p-4.text-left.text-blueGray-700
                  = user.last_name
                %td.border-t-0.px-6.align-middle.border-l-0.border-r-0.text-xs.whitespace-nowrap.p-4.text-left.text-blueGray-700
                  = user.username
                %td.border-t-0.px-6.align-middle.border-l-0.border-r-0.text-xs.whitespace-nowrap.p-4.text-left.text-blueGray-700
                  = user.email
                %td.border-t-0.px-6.align-center.border-l-0.border-r-0.text-xs.whitespace-nowrap.p-4
                  = link_to "Manage Roles", team_user_assign_roles_path(current_team, user.id), class: 'bg-yellow-500 text-white active:bg-indigo-600 text-xs font-bold uppercase px-3 py-1 rounded outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150'
                %td.border-t-0.px-6.align-center.border-l-0.border-r-0.text-xs.whitespace-nowrap.p-4
                  = link_to "View", team_user_path(team_id: current_team.id, id: user.id), class: 'bg-green-500 text-white active:bg-indigo-600 text-xs font-bold uppercase px-3 py-1 rounded outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150'
                %td.border-t-0.px-6.align-center.border-l-0.border-r-0.text-xs.whitespace-nowrap.p-4
                  - if current_team.check_owner(current_user.id) || current_user.id == user.id || @user_roles.include?('edit')
                    = link_to "Edit", edit_team_user_path(team_id: current_team.id, id: user.id), class: 'bg-indigo-500 text-white active:bg-indigo-600 text-xs font-bold uppercase px-3 py-1 rounded outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150'
                %td.border-t-0.px-6.align-middle.border-l-0.border-r-0.text-xs.whitespace-nowrap.p-4
                  - if current_team.check_owner(current_user.id) || current_user.id == user.id || @user_roles.include?('delete')
                    = link_to "Delete", team_user_path(team_id: current_team.id, id: user.id), data: { turbo_method: :delete }, class: 'bg-red-500 text-white active:bg-indigo-600 text-xs font-bold uppercase px-3 py-1 rounded outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150'

app/views/users/new.html.haml
.mx-auto.w-full{:class => "md:w-2/3"}
  %h1.font-bold.text-4xl New user
  = render "form", user: @user, path: team_users_path(current_team)
  = link_to "Back to users", team_users_path(current_team), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/users/show.html.haml
.mx-auto.w-full.flex{:class => "md:w-2/3"}
  .mx-auto
    - if notice.present?
      %p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block= notice
    = render @user
    - if current_team.check_owner(current_user.id) || current_user.id == @user.id || @user_roles.include?('edit')
      = link_to "Edit this user", edit_team_user_path(current_team, @user), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
    - if current_team.check_owner(current_user.id) || current_user.id == @user.id || @user_roles.include?('delete')
      .inline-block.ml-2
        = button_to "Destroy this user", team_user_path(current_team, @user), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium"
    = link_to "Back to users", team_users_path(current_team), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"