config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'dashboard#index'

  resources :teams do
    get :assign_members
    post :save_members
    resources :roles
    resources :users do 
      get :assign_roles
      post :save_roles
    end
  end
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :team
  has_many :roles_users
  has_many :users, through: :roles_users
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: %i[ show edit update destroy ]

  # GET /roles or /roles.json
  def index
    @roles = current_team.roles
  end

  # GET /roles/1 or /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles or /roles.json
  def create
    @role = Role.new(role_params)
    params[:role][:permissions] = params[:role][:permissions].reject(&:blank?)
    respond_to do |format|
      if @role.save
        format.html { redirect_to team_role_path(@role, team_id: current_team&.id), notice: "Role was successfully created." }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1 or /roles/1.json
  def update
    respond_to do |format|
      params[:role][:permissions] = params[:role][:permissions].reject(&:blank?)
      if @role.update(role_params)
        format.html { redirect_to team_role_path(@role, team_id: current_team&.id), notice: "Role was successfully updated." }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1 or /roles/1.json
  def destroy
    @role.destroy!

    respond_to do |format|
      format.html { redirect_to team_roles_path(team_id: current_team&.id), notice: "Role was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def role_params
      params.require(:role).permit(:name, :description, :user_id, :team_id, permissions: [])
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.haml
= form_with(model: role, url: path, class: "contents") do |form|
  = form.hidden_field :user_id, value: current_user.id
  = form.hidden_field :team_id, value: current_team.id
  - if role.errors.any?
    #error_explanation.bg-red-50.text-red-500.px-3.py-2.font-medium.rounded-lg.mt-3
      %h2
        = pluralize(role.errors.count, "error")
        prohibited this role from being saved:
      %ul
        - role.errors.each do |error|
          %li= error.full_message
  .my-5
    = form.label :name
    = form.text_field :name, required: true, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :description
    = form.text_area :description, required: true, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :permissions
    = form.select :permissions, options_for_select([['create', 'create'], ['edit', 'edit'], ['delete', 'delete']], selected: form.object&.permissions), multiple: true, required: true
  .inline
    = form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer"

app/views/roles/_role.html.haml
%div{:id => "#{dom_id role}"}
  %p.my-5
    %strong.block.font-medium.mb-1 Name:
    = role.name
  %p.my-5
    %strong.block.font-medium.mb-1 Description:
    = role.description
  %p.my-5
    %strong.block.font-medium.mb-1 Permission:
    = role.permissions&.compact.join(", ")
  - if action_name != "show" && current_user.id == role.user_id
    = link_to "Show this role", role, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
    = link_to "Edit this role", edit_role_path(role), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium"
    %hr.mt-6/

app/views/roles/edit.html.haml
.mx-auto.w-full{:class => "md:w-2/3"}
  %h1.font-bold.text-4xl Editing role
  = render "form", role: @role, path: team_role_path(team_id: current_team.id)
  = link_to "Show this role", team_role_path(@role, team_id: current_team.id), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
  = link_to "Back to roles", team_roles_path(team_id: current_team.id), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/roles/index.html.haml
.w-full
  - if notice.present?
    %p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block= notice
%section.py-1.bg-blueGray-50
  .w-full.mb-12.xl:mb-0.px-4.mx-auto.mt-24{class: "xl:w-8/12"}
    .relative.flex.flex-col.min-w-0.break-words.bg-white.w-full.mb-6.shadow-lg.rounded
      .rounded-t.mb-0.px-4.py-3.border-0
        .flex.flex-wrap.items-center
          .relative.w-full.px-4.max-w-full.flex-grow.flex-1
            %h3.font-semibold.text-base.text-blueGray-700 Roles
          .relative.w-full.px-4.max-w-full.flex-grow.flex-1.text-right
            - if @user_roles.include?('create') || current_team.check_owner(current_user.id)
              = link_to "Create Role", new_team_role_path(current_team), class: "bg-indigo-500 text-white active:bg-indigo-600 text-xs font-bold uppercase px-3 py-1 rounded outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150"
      .block.w-full.overflow-x-auto
        %table.items-center.bg-transparent.w-full.border-collapse
          %thead
            %tr
              %th.px-6.bg-blueGray-50.text-blueGray-500.align-middle.border.border-solid.border-blueGray-100.py-3.text-xs.uppercase.border-l-0.border-r-0.whitespace-nowrap.font-semibold.text-left
                Role Name
              %th.px-6.bg-blueGray-50.text-blueGray-500.align-middle.border.border-solid.border-blueGray-100.py-3.text-xs.uppercase.border-l-0.border-r-0.whitespace-nowrap.font-semibold.text-left
                Permissions
              %th.px-6.bg-blueGray-50.text-blueGray-500.align-middle.border.border-solid.border-blueGray-100.py-3.text-xs.uppercase.border-l-0.border-r-0.whitespace-nowrap.font-semibold.text-left
                View
              %th.px-6.bg-blueGray-50.text-blueGray-500.align-middle.border.border-solid.border-blueGray-100.py-3.text-xs.uppercase.border-l-0.border-r-0.whitespace-nowrap.font-semibold.text-left
                Edit
              %th.px-6.bg-blueGray-50.text-blueGray-500.align-middle.border.border-solid.border-blueGray-100.py-3.text-xs.uppercase.border-l-0.border-r-0.whitespace-nowrap.font-semibold.text-left
                Delete
          %tbody
            - @roles&.each do |role|
              %tr
                %td.border-t-0.px-6.align-middle.border-l-0.border-r-0.text-xs.whitespace-nowrap.p-4.text-left.text-blueGray-700
                  = role.name
                %td.border-t-0.px-6.align-middle.border-l-0.border-r-0.text-xs.whitespace-nowrap.p-4.text-left.text-blueGray-700
                  = role.permissions.join(", ")
                %td.border-t-0.px-6.align-center.border-l-0.border-r-0.text-xs.whitespace-nowrap.p-4
                  = link_to "View", team_role_path(team_id: current_team.id, id: role.id), class: 'bg-green-500 text-white active:bg-indigo-600 text-xs font-bold uppercase px-3 py-1 rounded outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150'
                %td.border-t-0.px-6.align-center.border-l-0.border-r-0.text-xs.whitespace-nowrap.p-4
                  - if current_user.id == role.user_id || @user_roles.include?('edit')
                    = link_to "Edit", edit_team_role_path(team_id: current_team.id, id: role.id), class: 'bg-indigo-500 text-white active:bg-indigo-600 text-xs font-bold uppercase px-3 py-1 rounded outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150'
                %td.border-t-0.px-6.align-middle.border-l-0.border-r-0.text-xs.whitespace-nowrap.p-4
                  - if current_user.id == role.user_id || @user_roles.include?('delete')
                    = link_to "Delete", team_role_path(team_id: current_team.id, id: role.id), data: { turbo_method: :delete }, class: 'bg-red-500 text-white active:bg-indigo-600 text-xs font-bold uppercase px-3 py-1 rounded outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150'

app/views/roles/new.html.haml
.mx-auto.w-full{:class => "md:w-2/3"}
  %h1.font-bold.text-4xl New role
  = render "form", role: @role, path: team_roles_path(team_id: current_team.id)
  = link_to "Back to roles", team_roles_path(team_id: current_team.id), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/roles/show.html.haml
.mx-auto.w-full.flex{:class => "md:w-2/3"}
  .mx-auto
    - if notice.present?
      %p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block= notice
    = render @role
    - if @user_roles.include?('edit') 
      = link_to "Edit this role", edit_team_role_path(@role, team_id: current_team.id), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
    - if @user_roles.include?('delete')
      .inline-block.ml-2
        = button_to "Destroy this role", team_role_path(@role, team_id: current_team.id), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium"
    = link_to "Back to roles", team_roles_path(team_id: current_team.id), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"